### ISSUE TITLE
Recursive query not working

### ISSUE THREAD

**Issue by RicsiToth** [matfyz-sk/courses-backend#33]
when inserting data which are required. To reproduce use query:
`mutation {
  insert_courses_Course (
    courses_name: "123"
    courses_description: "123"
    courses_abbreviation: "123"
  ) {
    _id
  }
}`

Then when queried courses_Course by id and the body contains object from ontology for example courses_covers the response is error the back-end returns: 
`UltraGraphQL 2023-05-04 23:02:30 ERROR GeneralError:55 -
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "org.hypergraphql.datafetching.services.resultmodel.ObjectResult.generateJSON()" is null
        at org.hypergraphql.datafetching.services.resultmodel.ObjectResult.lambda$generateJSON$2(ObjectResult.java:181)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:200)
        at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.hypergraphql.datafetching.services.resultmodel.ObjectResult.generateJSON(ObjectResult.java:189)
        at org.hypergraphql.datafetching.services.resultmodel.QueryRootResult.generateJSON(QueryRootResult.java:38)
        at org.hypergraphql.services.HGQLQueryService.results(HGQLQueryService.java:99)
        at org.hypergraphql.services.HGQLRequestService.results(HGQLRequestService.java:70)
        at org.hypergraphql.Controller.lambda$startSpark$3(Controller.java:166)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1598)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:833)
`

The GUI for graphql returns:
`<html><body><h2>500 Internal Server Error</h2></body></html>`

The query example for error is: 
`{
  courses_Course(_id: "INSERT HERE THE ID") {
    _id
    courses_createdAt
    courses_name
    courses_description
    courses_abbreviation
    courses_covers {
      _id
    }
    courses_hasAdmin {
      _id
    }
  }
}`

**Comment by bl96** [comment]
A method was called on null object, causing NPE. The object was the result of the generateJson() method. The method should return the null as the value does not exist, but the method should not be called when the object is null. Added check for null. Fix will be available in UGQL version 1.2.1.
